package gui;

import dao.PlaylistDataInterface;
import domain.Profile;
import gui.helpers.SimpleListModel;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author parhy569
 */
public class AddPlayList extends javax.swing.JDialog {

	private Profile signedInProfile;
	private SimpleListModel myModel;
	private PlaylistDataInterface playdao;
	private String recipeID;

	/**
	 * Creates new form AddPlayList
	 */
	public AddPlayList(java.awt.Window parent, boolean modal, Profile signedInProfile, PlaylistDataInterface playdao, String recipeID) {
		super(parent);
		super.setModal(modal);
		this.signedInProfile = signedInProfile;
		this.recipeID = recipeID;
		this.playdao = playdao;
		initComponents();
		myModel = new SimpleListModel();
		myModel.updateItems(playdao.getAllPlaylists(signedInProfile.getUserID()));
		playlistsExisting.setModel(myModel);
                this.setResizable(false);
                Color backgroundColor = new Color(229, 214, 201);
                this.getContentPane().setBackground(backgroundColor);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        profileCreateButton = new javax.swing.JButton();
        profileCloseButton = new javax.swing.JButton();
        recipeEditButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        addToPlaylistClose = new javax.swing.JButton();
        choosePlayListButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        playlistsExisting = new javax.swing.JList<>();

        jLabel2.setBackground(new java.awt.Color(239, 240, 234));
        jLabel2.setFont(new java.awt.Font("맑은 고딕", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(75, 68, 41));
        jLabel2.setText("P L A Y L I S T");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel6.setBackground(new java.awt.Color(239, 240, 234));
        jLabel6.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(139, 191, 166));
        jLabel6.setText("Bone");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setBackground(new java.awt.Color(239, 240, 234));
        jLabel7.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 167, 167));
        jLabel7.setText("Apple");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setBackground(new java.awt.Color(239, 240, 234));
        jLabel8.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(139, 191, 166));
        jLabel8.setText("Tea");
        jLabel8.setName("jLabel8"); // NOI18N

        profileCreateButton.setBackground(new java.awt.Color(75, 68, 41));
        profileCreateButton.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        profileCreateButton.setForeground(new java.awt.Color(255, 255, 255));
        profileCreateButton.setText("CREATE");
        profileCreateButton.setName("profileCreateButton"); // NOI18N
        profileCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileCreateButtonActionPerformed(evt);
            }
        });

        profileCloseButton.setBackground(new java.awt.Color(75, 68, 41));
        profileCloseButton.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        profileCloseButton.setForeground(new java.awt.Color(255, 255, 255));
        profileCloseButton.setText("CLOSE");
        profileCloseButton.setName("profileCloseButton"); // NOI18N
        profileCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileCloseButtonActionPerformed(evt);
            }
        });

        recipeEditButton.setBackground(new java.awt.Color(75, 68, 41));
        recipeEditButton.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        recipeEditButton.setForeground(new java.awt.Color(255, 255, 255));
        recipeEditButton.setText("EDIT");
        recipeEditButton.setName("recipeEditButton"); // NOI18N
        recipeEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipeEditButtonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BAT");

        jLabel3.setBackground(new java.awt.Color(239, 240, 234));
        jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(75, 68, 41));
        jLabel3.setText("C O L L E C T I O N");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel9.setBackground(new java.awt.Color(239, 240, 234));
        jLabel9.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(139, 191, 166));
        jLabel9.setText("Bone");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setBackground(new java.awt.Color(239, 240, 234));
        jLabel10.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 167, 167));
        jLabel10.setText("Apple");
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setBackground(new java.awt.Color(239, 240, 234));
        jLabel11.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(139, 191, 166));
        jLabel11.setText("Tea");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setBackground(new java.awt.Color(239, 240, 234));
        jLabel12.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(56, 133, 96));
        jLabel12.setText("Collection:");
        jLabel12.setName("jLabel12"); // NOI18N

        addToPlaylistClose.setBackground(new java.awt.Color(75, 68, 41));
        addToPlaylistClose.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        addToPlaylistClose.setForeground(new java.awt.Color(255, 255, 255));
        addToPlaylistClose.setText("CLOSE");
        addToPlaylistClose.setName("addToPlaylistClose"); // NOI18N
        addToPlaylistClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToPlaylistCloseActionPerformed(evt);
            }
        });

        choosePlayListButton.setBackground(new java.awt.Color(75, 68, 41));
        choosePlayListButton.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        choosePlayListButton.setForeground(new java.awt.Color(255, 255, 255));
        choosePlayListButton.setText("CHOOSE");
        choosePlayListButton.setName("choosePlayListButton"); // NOI18N
        choosePlayListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePlayListButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        playlistsExisting.setName("playlistsExisting"); // NOI18N
        jScrollPane1.setViewportView(playlistsExisting);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(choosePlayListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                                .addComponent(addToPlaylistClose, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel9)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel10)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel11)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addToPlaylistClose)
                    .addComponent(choosePlayListButton))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void profileCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileCreateButtonActionPerformed

		/*
      ProductReport report = new ProductReport(this, true, dao);
      report.setLocationRelativeTo(this);
      report.setVisible(true);
		 */
   }//GEN-LAST:event_profileCreateButtonActionPerformed

   private void profileCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileCloseButtonActionPerformed
		// TODO add your handling code here:
		dispose();
   }//GEN-LAST:event_profileCloseButtonActionPerformed

   private void addToPlaylistCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToPlaylistCloseActionPerformed
		// TODO add your handling code here:
		dispose();
   }//GEN-LAST:event_addToPlaylistCloseActionPerformed

   private void recipeEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipeEditButtonActionPerformed

   }//GEN-LAST:event_recipeEditButtonActionPerformed

   private void choosePlayListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePlayListButtonActionPerformed
		String selectedPlaylist = playlistsExisting.getSelectedValue();
		System.out.println(selectedPlaylist);
		if (!(selectedPlaylist.equals(""))) {
			List<String> contentsOfPlaylist = new ArrayList<>();
			contentsOfPlaylist.addAll(playdao.getRecipesFromPlaylist(
					  signedInProfile.getUserID(), selectedPlaylist));
                        if (!(contentsOfPlaylist.contains(recipeID))){
                            contentsOfPlaylist.add(recipeID);
                        }
			playdao.addToPlaylist(signedInProfile.getUserID(), selectedPlaylist, contentsOfPlaylist);
			dispose();

		}

   }//GEN-LAST:event_choosePlayListButtonActionPerformed

//	/**
//	 * @param args the command line arguments
//	 */
//	public static void main(String args[]) {
//		/* Set the Nimbus look and feel */
//		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//		 */
//		try {
//			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//				if ("Nimbus".equals(info.getName())) {
//					javax.swing.UIManager.setLookAndFeel(info.getClassName());
//					break;
//				}
//			}
//		} catch (ClassNotFoundException ex) {
//			java.util.logging.Logger.getLogger(AddPlayList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (InstantiationException ex) {
//			java.util.logging.Logger.getLogger(AddPlayList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (IllegalAccessException ex) {
//			java.util.logging.Logger.getLogger(AddPlayList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
//			java.util.logging.Logger.getLogger(AddPlayList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		}
//		//</editor-fold>
//
//		/* Create and display the dialog */
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				AddPlayList dialog = new AddPlayList(new javax.swing.JFrame(), true);
//				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//					@Override
//					public void windowClosing(java.awt.event.WindowEvent e) {
//						System.exit(0);
//					}
//				});
//				dialog.setVisible(true);
//			}
//		});
//	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToPlaylistClose;
    private javax.swing.JButton choosePlayListButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> playlistsExisting;
    private javax.swing.JButton profileCloseButton;
    private javax.swing.JButton profileCreateButton;
    private javax.swing.JButton recipeEditButton;
    // End of variables declaration//GEN-END:variables
}
