package gui;

import dao.PlaylistDataInterface;
import dao.ProfileDataInterface;
import domain.Profile;
import java.awt.Color;
import java.util.Collection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author parhy569
 */
public class CreatePlayList extends javax.swing.JDialog {

	private MainMenu mm;
	private PlaylistDataInterface playdao;
	private ProfileDataInterface prodao;
        final JPanel panel = new JPanel();

	/**
	 * Creates new form CreatePlayList
	 */
	public CreatePlayList(java.awt.Frame parent, boolean modal, ProfileDataInterface prodao, PlaylistDataInterface playdao, MainMenu mm) {
		super(parent, modal);
		this.mm = mm;
		this.playdao = playdao;
		this.prodao = prodao;
		initComponents();
                this.setResizable(false);
                Color backgroundColor = new Color(229, 214, 201);
                this.getContentPane().setBackground(backgroundColor);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtPlaylistName = new javax.swing.JTextField();
        playlistCreateButton = new javax.swing.JButton();
        playlistCloseButton = new javax.swing.JButton();

        jLabel9.setBackground(new java.awt.Color(239, 240, 234));
        jLabel9.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(139, 191, 166));
        jLabel9.setText("Bone");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setBackground(new java.awt.Color(239, 240, 234));
        jLabel10.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 167, 167));
        jLabel10.setText("Apple");
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setBackground(new java.awt.Color(239, 240, 234));
        jLabel11.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(139, 191, 166));
        jLabel11.setText("Tea");
        jLabel11.setName("jLabel11"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setBackground(new java.awt.Color(239, 240, 234));
        jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(75, 68, 41));
        jLabel3.setText("C O L L E C T I O N");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel12.setBackground(new java.awt.Color(239, 240, 234));
        jLabel12.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(139, 191, 166));
        jLabel12.setText("Bone");
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel13.setBackground(new java.awt.Color(239, 240, 234));
        jLabel13.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 167, 167));
        jLabel13.setText("Apple");
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel14.setBackground(new java.awt.Color(239, 240, 234));
        jLabel14.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(139, 191, 166));
        jLabel14.setText("Tea");
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel15.setBackground(new java.awt.Color(239, 240, 234));
        jLabel15.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(56, 133, 96));
        jLabel15.setText("Name:");
        jLabel15.setName("jLabel15"); // NOI18N

        txtPlaylistName.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        txtPlaylistName.setName("txtPlaylistName"); // NOI18N
        txtPlaylistName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlaylistNameActionPerformed(evt);
            }
        });

        playlistCreateButton.setBackground(new java.awt.Color(75, 68, 41));
        playlistCreateButton.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        playlistCreateButton.setForeground(new java.awt.Color(255, 255, 255));
        playlistCreateButton.setText("CREATE");
        playlistCreateButton.setName("playlistCreateButton"); // NOI18N
        playlistCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playlistCreateButtonActionPerformed(evt);
            }
        });

        playlistCloseButton.setBackground(new java.awt.Color(75, 68, 41));
        playlistCloseButton.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        playlistCloseButton.setForeground(new java.awt.Color(255, 255, 255));
        playlistCloseButton.setText("CLOSE");
        playlistCloseButton.setName("playlistCloseButton"); // NOI18N
        playlistCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playlistCloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPlaylistName, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playlistCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playlistCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel13)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel14)))
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtPlaylistName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playlistCreateButton)
                    .addComponent(playlistCloseButton))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void txtPlaylistNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlaylistNameActionPerformed
		// TODO add your handling code here:
   }//GEN-LAST:event_txtPlaylistNameActionPerformed

   private void playlistCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playlistCreateButtonActionPerformed
		String playlistName = txtPlaylistName.getText();
		if (!(playlistName.equals(" "))) {
			// Get the signed in profile
			Profile signedInProfile = mm.getSignedInProfile();
			// Get the user name
			String userID = signedInProfile.getUserID();
                        
                        // Error check
                        Collection<String> errorCheck = playdao.getPlaylistByName(userID, playlistName);
                        System.out.println(errorCheck);
                        
                        if (errorCheck == null){

                            // Create a new playlist, and set UserID to profile's ID
                            String playlistID = playdao.newPlaylist(userID, playlistName);
                            // Update the signedIn Profile with the playlist
                            signedInProfile.addToPlaylist(playlistID);
                            // Update the sql's profile with an updated playlist
                            prodao.updateAProfilesPlaylists(signedInProfile);
                            mm.signIn(signedInProfile);
                            dispose();
                        } else {
                JOptionPane.showMessageDialog(panel, "Cannot create a playlist with an existing name!", "Warning!", JOptionPane.ERROR_MESSAGE);
                        }
		}
   }//GEN-LAST:event_playlistCreateButtonActionPerformed

   private void playlistCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playlistCloseButtonActionPerformed
		// TODO add your handling code here:
		dispose();
   }//GEN-LAST:event_playlistCloseButtonActionPerformed

//	/**
//	 * @param args the command line arguments
//	 */
//	public static void main(String args[]) {
//		/* Set the Nimbus look and feel */
//		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//		 */
//		try {
//			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//				if ("Nimbus".equals(info.getName())) {
//					javax.swing.UIManager.setLookAndFeel(info.getClassName());
//					break;
//				}
//			}
//		} catch (ClassNotFoundException ex) {
//			java.util.logging.Logger.getLogger(CreatePlayList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (InstantiationException ex) {
//			java.util.logging.Logger.getLogger(CreatePlayList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (IllegalAccessException ex) {
//			java.util.logging.Logger.getLogger(CreatePlayList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
//			java.util.logging.Logger.getLogger(CreatePlayList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		}
//		//</editor-fold>
//
//		/* Create and display the dialog */
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				CreatePlayList dialog = new CreatePlayList(new javax.swing.JFrame(), true);
//				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//					@Override
//					public void windowClosing(java.awt.event.WindowEvent e) {
//						System.exit(0);
//					}
//				});
//				dialog.setVisible(true);
//			}
//		});
//	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton playlistCloseButton;
    private javax.swing.JButton playlistCreateButton;
    private javax.swing.JTextField txtPlaylistName;
    // End of variables declaration//GEN-END:variables
}
