package gui;

import dao.PlaylistDAOv2;
import dao.RecipeDAOv2;
import dao.ProfileDAOv2;
import domain.Profile;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author dinjo998
 */
public class DevDatabaseAdmin extends javax.swing.JDialog {
	private final RecipeDAOv2 recdao = new RecipeDAOv2();
	private final ProfileDAOv2 prodao = new ProfileDAOv2();
	private final PlaylistDAOv2 playdao = new PlaylistDAOv2();
	/**
	 * Creates new form MainMenu
	 * @param dao
	 */
	public DevDatabaseAdmin(java.awt.Window parent, boolean modal) {
            super(parent);
            super.setModal(modal);
            initComponents();
            this.setResizable(false);
            Color backgroundColor = new Color(229, 214, 201);
                this.getContentPane().setBackground(backgroundColor);
    }
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel2 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      jLabel1 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      checkTablesButton = new javax.swing.JButton();
      closeButton = new javax.swing.JButton();
      resetTablesButton = new javax.swing.JButton();
      rerunInitialButton = new javax.swing.JButton();
      jLabel7 = new javax.swing.JLabel();
      sampleDataButton = new javax.swing.JButton();
      viewProfilesButton = new javax.swing.JButton();

      jLabel2.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel2.setText("Product Administration");
      jLabel2.setName("jLabel2"); // NOI18N

      jLabel5.setBackground(new java.awt.Color(239, 240, 234));
      jLabel5.setFont(new java.awt.Font("맑은 고딕", 1, 36)); // NOI18N
      jLabel5.setForeground(new java.awt.Color(75, 68, 41));
      jLabel5.setText("NEW R E C I P E");
      jLabel5.setName("jLabel5"); // NOI18N

      setBackground(new java.awt.Color(239, 240, 234));

      jLabel1.setBackground(new java.awt.Color(239, 240, 234));
      jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(75, 68, 41));
      jLabel1.setText("BONE");
      jLabel1.setName("jLabel1"); // NOI18N

      jLabel3.setBackground(new java.awt.Color(239, 240, 234));
      jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
      jLabel3.setForeground(new java.awt.Color(153, 0, 0));
      jLabel3.setText("APPLE");
      jLabel3.setName("jLabel3"); // NOI18N

      jLabel4.setBackground(new java.awt.Color(239, 240, 234));
      jLabel4.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
      jLabel4.setForeground(new java.awt.Color(75, 68, 41));
      jLabel4.setText("TEA");
      jLabel4.setName("jLabel4"); // NOI18N

      checkTablesButton.setBackground(new java.awt.Color(239, 240, 234));
      checkTablesButton.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
      checkTablesButton.setForeground(new java.awt.Color(71, 71, 71));
      checkTablesButton.setText("Check if Tables exist in Database");
      checkTablesButton.setName("checkTablesButton"); // NOI18N
      checkTablesButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            checkTablesButtonActionPerformed(evt);
         }
      });

      closeButton.setBackground(new java.awt.Color(75, 68, 41));
      closeButton.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
      closeButton.setForeground(new java.awt.Color(255, 255, 255));
      closeButton.setText("CLOSE");
      closeButton.setName("closeButton"); // NOI18N
      closeButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            closeButtonActionPerformed(evt);
         }
      });

      resetTablesButton.setBackground(new java.awt.Color(239, 240, 234));
      resetTablesButton.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
      resetTablesButton.setForeground(new java.awt.Color(71, 71, 71));
      resetTablesButton.setText("Reset Tables in Database");
      resetTablesButton.setName("resetTablesButton"); // NOI18N
      resetTablesButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            resetTablesButtonActionPerformed(evt);
         }
      });

      rerunInitialButton.setBackground(new java.awt.Color(239, 240, 234));
      rerunInitialButton.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
      rerunInitialButton.setForeground(new java.awt.Color(71, 71, 71));
      rerunInitialButton.setText("Rerun Initial Check");
      rerunInitialButton.setName("rerunInitialButton"); // NOI18N
      rerunInitialButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            rerunInitialButtonActionPerformed(evt);
         }
      });

      jLabel7.setBackground(new java.awt.Color(239, 240, 234));
      jLabel7.setFont(new java.awt.Font("맑은 고딕", 1, 36)); // NOI18N
      jLabel7.setForeground(new java.awt.Color(75, 68, 41));
      jLabel7.setText("Database Admin");
      jLabel7.setName("jLabel7"); // NOI18N

      sampleDataButton.setBackground(new java.awt.Color(239, 240, 234));
      sampleDataButton.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
      sampleDataButton.setForeground(new java.awt.Color(71, 71, 71));
      sampleDataButton.setText("Populate Database with Sample Recipes");
      sampleDataButton.setName("sampleDataButton"); // NOI18N
      sampleDataButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            sampleDataButtonActionPerformed(evt);
         }
      });

      viewProfilesButton.setBackground(new java.awt.Color(239, 240, 234));
      viewProfilesButton.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
      viewProfilesButton.setForeground(new java.awt.Color(71, 71, 71));
      viewProfilesButton.setText("View Profiles in Database");
      viewProfilesButton.setName("viewProfilesButton"); // NOI18N
      viewProfilesButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            viewProfilesButtonActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 67, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jLabel7)
                     .addComponent(sampleDataButton)
                     .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(resetTablesButton)
                           .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel1)
                              .addGap(9, 9, 9)
                              .addComponent(jLabel3)))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(viewProfilesButton)
                        .addGap(50, 50, 50)))
                  .addGap(57, 57, 57))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(rerunInitialButton)
                  .addGap(126, 126, 126))))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(checkTablesButton)
                  .addGap(84, 84, 84))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(156, 156, 156))))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(jLabel3)
               .addComponent(jLabel4))
            .addGap(18, 18, 18)
            .addComponent(resetTablesButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(checkTablesButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(rerunInitialButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(sampleDataButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(viewProfilesButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
            .addComponent(closeButton)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void checkTablesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTablesButtonActionPerformed
        recdao.checkTables();
    }//GEN-LAST:event_checkTablesButtonActionPerformed

   private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
      // TODO add your handling code here:
      dispose();
   }//GEN-LAST:event_closeButtonActionPerformed

    private void resetTablesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetTablesButtonActionPerformed
        recdao.clearDB();
        recdao.createDB();
		  Profile dev = new Profile();
		  dev.setName("Dev");
		  String userID = UUID.randomUUID().toString();
		  dev.setUserID(userID);
		  List<String> playlists = new ArrayList<>();
		  dev.setPlaylists(playlists);
//		  dev.addToPlaylist(playdao.initialFavouriteSetup(userID));
//      dev.addToPlaylist(playdao.initialHistorySetup(userID));
		  
		  prodao.save(dev);
    }//GEN-LAST:event_resetTablesButtonActionPerformed

    private void rerunInitialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rerunInitialButtonActionPerformed
        recdao.initial();
    }//GEN-LAST:event_rerunInitialButtonActionPerformed

   private void sampleDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sampleDataButtonActionPerformed
		try {
			recdao.sampleRecipes();
		} catch (FileNotFoundException ex) {
			Logger.getLogger(DevDatabaseAdmin.class.getName()).log(Level.SEVERE, null, ex);
		}
   }//GEN-LAST:event_sampleDataButtonActionPerformed

   private void viewProfilesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfilesButtonActionPerformed
//      ViewProfiles viewProf = new ViewProfiles(this, true, prodao, this);
//		viewProf.setLocationRelativeTo(this);
//		viewProf.setVisible(true);
   }//GEN-LAST:event_viewProfilesButtonActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton checkTablesButton;
   private javax.swing.JButton closeButton;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JButton rerunInitialButton;
   private javax.swing.JButton resetTablesButton;
   private javax.swing.JButton sampleDataButton;
   private javax.swing.JButton viewProfilesButton;
   // End of variables declaration//GEN-END:variables
}
