package gui;

import dao.ProfileDataInterface;
import dao.RecipeDataInterface;
import dao.PlaylistDataInterface;
import java.awt.Color;

/**
 *
 * @author dinjo998
 */
public class Help extends javax.swing.JFrame {

    private int count = 1;

    /**
     * Creates new Help window
     */
    public Help() {
        initComponents();
        this.setResizable(false);
        Color backgroundColor = new Color(229, 214, 201);
        this.getContentPane().setBackground(backgroundColor);
    }
    
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      closeButton = new javax.swing.JButton();
      previousButton = new javax.swing.JButton();
      nextButton = new javax.swing.JButton();
      jLabelHelp = new javax.swing.JLabel();
      jLabel1 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("BAT");
      setBackground(new java.awt.Color(0, 0, 0));
      setMinimumSize(new java.awt.Dimension(374, 465));
      setResizable(false);

      closeButton.setBackground(new java.awt.Color(75, 68, 41));
      closeButton.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
      closeButton.setForeground(new java.awt.Color(255, 255, 255));
      closeButton.setText("CLOSE");
      closeButton.setName("closeButton"); // NOI18N
      closeButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            closeButtonActionPerformed(evt);
         }
      });

      previousButton.setBackground(new java.awt.Color(75, 68, 41));
      previousButton.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
      previousButton.setForeground(new java.awt.Color(255, 255, 255));
      previousButton.setText("PREVIOUS");
      previousButton.setName("previousButton"); // NOI18N
      previousButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            previousButtonActionPerformed(evt);
         }
      });

      nextButton.setBackground(new java.awt.Color(75, 68, 41));
      nextButton.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
      nextButton.setForeground(new java.awt.Color(255, 255, 255));
      nextButton.setText("NEXT");
      nextButton.setName("nextButton"); // NOI18N
      nextButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            nextButtonActionPerformed(evt);
         }
      });

      jLabelHelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabelHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/help/help1.jpg"))); // NOI18N
      jLabelHelp.setFocusable(false);
      jLabelHelp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      jLabelHelp.setMaximumSize(new java.awt.Dimension(612, 409));
      jLabelHelp.setMinimumSize(new java.awt.Dimension(612, 409));
      jLabelHelp.setName("jLabelHelp"); // NOI18N
      jLabelHelp.setPreferredSize(new java.awt.Dimension(612, 409));
      jLabelHelp.setRequestFocusEnabled(false);

      jLabel1.setBackground(new java.awt.Color(239, 240, 234));
      jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 36)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(75, 68, 41));
      jLabel1.setText("H E L P");
      jLabel1.setName("jLabel1"); // NOI18N

      jLabel3.setBackground(new java.awt.Color(239, 240, 234));
      jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel3.setForeground(new java.awt.Color(139, 191, 166));
      jLabel3.setText("Bone");
      jLabel3.setName("jLabel3"); // NOI18N

      jLabel4.setBackground(new java.awt.Color(239, 240, 234));
      jLabel4.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel4.setForeground(new java.awt.Color(255, 167, 167));
      jLabel4.setText("Apple");
      jLabel4.setName("jLabel4"); // NOI18N

      jLabel5.setBackground(new java.awt.Color(239, 240, 234));
      jLabel5.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel5.setForeground(new java.awt.Color(139, 191, 166));
      jLabel5.setText("Tea");
      jLabel5.setName("jLabel5"); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(jLabelHelp, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(previousButton)
                  .addGap(18, 18, 18)
                  .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(293, 293, 293))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(jLabel3)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jLabel4)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jLabel5)
                  .addGap(210, 210, 210))))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap(13, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(5, 5, 5)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(jLabel4)
               .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabelHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(closeButton)
               .addComponent(previousButton)
               .addComponent(nextButton))
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
       dispose();
   }//GEN-LAST:event_closeButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
//        if(count == 1){
//            count = 3;
//        } else{
//            count--;
//        }
        jLabelHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/help/help"+(count)+".jpg")));
    }//GEN-LAST:event_previousButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
//        if(count == 3){
//            count = 1;
//        } else{
//            count++;
//        }
        jLabelHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/help/help"+(count)+".jpg")));
    }//GEN-LAST:event_nextButtonActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton closeButton;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabelHelp;
   private javax.swing.JButton nextButton;
   private javax.swing.JButton previousButton;
   // End of variables declaration//GEN-END:variables
}
