package gui;

import dao.ProfileDataInterface;
import dao.RecipeDataInterface;
import dao.PlaylistDataInterface;
import domain.Profile;
import domain.Recipe;
//import java.applet.Applet;
//import java.applet.AudioClip;
import java.awt.Color;
//import java.io.File;
//import java.io.FileInputStream;
import java.io.InputStream;
//import java.net.MalformedURLException;
//import java.net.URL;
//import java.util.logging.Level;
//import java.util.logging.Logger;
//import javax.sound.sampled.AudioInputStream;
//import javax.swing.JOptionPane;

/**
 *
 * @author dinjo998
 */
public class MainMenu extends javax.swing.JFrame {

	private final RecipeDataInterface recdao;
	private final ProfileDataInterface prodao;
	private final PlaylistDataInterface playdao;
	private Profile signedInProfile;

	/**
	 * Creates new form MainMenu
	 *
	 * @param recdao
	 * @param prodao
	 */
	public MainMenu(RecipeDataInterface recdao, ProfileDataInterface prodao, PlaylistDataInterface playdao) {
		initComponents();
		this.recdao = recdao;
		this.prodao = prodao;
		this.playdao = playdao;
		this.setResizable(false);
		Color backgroundColor = new Color(229, 214, 201);
		this.getContentPane().setBackground(backgroundColor);
	}

	public void signIn(Profile profile) {
		signedInProfile = profile;
		if (signedInProfile != null) {
			labelWelcome.setText("Welcome, " + signedInProfile.getName());
			signInButton.setText("Sign out");
			jMenuSignIn.setText("Sign Out");
			revalidate();
			repaint();
		} 
		if (signedInProfile != null && "Dev".equals(signedInProfile.getName())) {
			jMenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/help1_icon.png")));
			jMenuHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/help1_icon.png")));
			jMenuAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/help1_icon.png")));
			jMenuNewRecipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/help1_icon.png")));
			jMenuPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/help1_icon.png")));
			jMenuSearchRecipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/help1_icon.png")));
			jMenuSignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/help1_icon.png")));
			jMenuSuggest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/help1_icon.png")));
			jMenuCreateProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/help1_icon.png")));
			jMenuViewProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/help1_icon.png")));
			revalidate();
			repaint();
		}
	}

	public void signOut() {
		if (signedInProfile != null && "Dev".equals(signedInProfile.getName())) {
			jMenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
			jMenuHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
			jMenuAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
			jMenuNewRecipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
			jMenuPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
			jMenuSearchRecipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
			jMenuSignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
			jMenuSuggest.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
			jMenuCreateProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
			jMenuViewProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
		}
		labelWelcome.setText("Welcome. Please Sign In.");
		signInButton.setText("Sign In");
		signedInProfile = null;
		revalidate();
		repaint();
	}

	public Profile getSignedInProfile() {
		return signedInProfile;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      playlistButton = new javax.swing.JButton();
      searchButton = new javax.swing.JButton();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      newRecipeButton = new javax.swing.JButton();
      signInButton = new javax.swing.JButton();
      suggestButton = new javax.swing.JButton();
      labelWelcome = new javax.swing.JLabel();
      jMenuBar1 = new javax.swing.JMenuBar();
      File = new javax.swing.JMenu();
      jMenuNewRecipe = new javax.swing.JMenuItem();
      jMenuSearchRecipe = new javax.swing.JMenuItem();
      jSeparator1 = new javax.swing.JPopupMenu.Separator();
      jMenuPlaylist = new javax.swing.JMenuItem();
      jMenuSuggest = new javax.swing.JMenuItem();
      jSeparator2 = new javax.swing.JPopupMenu.Separator();
      jMenuExit = new javax.swing.JMenuItem();
      Profile = new javax.swing.JMenu();
      jMenuViewProfile = new javax.swing.JMenuItem();
      jMenuCreateProfile = new javax.swing.JMenuItem();
      jSeparator3 = new javax.swing.JPopupMenu.Separator();
      jMenuSignIn = new javax.swing.JMenuItem();
      Help = new javax.swing.JMenu();
      jMenuHelp = new javax.swing.JMenuItem();
      jSeparator4 = new javax.swing.JPopupMenu.Separator();
      jMenuAbout = new javax.swing.JMenuItem();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("BAT");
      setBackground(new java.awt.Color(0, 0, 0));
      setMaximumSize(new java.awt.Dimension(374, 465));
      setMinimumSize(new java.awt.Dimension(374, 465));
      setResizable(false);

      jLabel1.setBackground(new java.awt.Color(239, 240, 234));
      jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(56, 133, 96));
      jLabel1.setText("BONE");
      jLabel1.setName("jLabel1"); // NOI18N

      playlistButton.setBackground(new java.awt.Color(56, 133, 96));
      playlistButton.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
      playlistButton.setForeground(new java.awt.Color(255, 255, 255));
      playlistButton.setText("RECIPE COLLECTIONS");
      playlistButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      playlistButton.setName("playlistButton"); // NOI18N
      playlistButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            playlistButtonActionPerformed(evt);
         }
      });

      searchButton.setBackground(new java.awt.Color(56, 133, 96));
      searchButton.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
      searchButton.setForeground(new java.awt.Color(255, 255, 255));
      searchButton.setText("S E A R C H");
      searchButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      searchButton.setName("searchButton"); // NOI18N
      searchButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            searchButtonActionPerformed(evt);
         }
      });

      jLabel3.setBackground(new java.awt.Color(239, 240, 234));
      jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
      jLabel3.setForeground(new java.awt.Color(153, 0, 0));
      jLabel3.setText("APPLE");
      jLabel3.setName("jLabel3"); // NOI18N

      jLabel4.setBackground(new java.awt.Color(239, 240, 234));
      jLabel4.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
      jLabel4.setForeground(new java.awt.Color(56, 133, 96));
      jLabel4.setText("TEA");
      jLabel4.setName("jLabel4"); // NOI18N

      jLabel6.setBackground(new java.awt.Color(239, 240, 234));
      jLabel6.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel6.setForeground(new java.awt.Color(174, 174, 173));
      jLabel6.setText("Bon Appétit ");
      jLabel6.setName("jLabel6"); // NOI18N

      newRecipeButton.setBackground(new java.awt.Color(56, 133, 96));
      newRecipeButton.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
      newRecipeButton.setForeground(new java.awt.Color(255, 255, 255));
      newRecipeButton.setText("NEW R E C I P E");
      newRecipeButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      newRecipeButton.setName("newRecipeButton"); // NOI18N
      newRecipeButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            newRecipeButtonActionPerformed(evt);
         }
      });

      signInButton.setBackground(new java.awt.Color(239, 240, 234));
      signInButton.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
      signInButton.setForeground(new java.awt.Color(71, 71, 71));
      signInButton.setText("Sign In");
      signInButton.setName("signInButton"); // NOI18N
      signInButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            signInButtonActionPerformed(evt);
         }
      });

      suggestButton.setBackground(new java.awt.Color(56, 133, 96));
      suggestButton.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
      suggestButton.setForeground(new java.awt.Color(255, 255, 255));
      suggestButton.setText("RECIPE SUGGESTIONS");
      suggestButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      suggestButton.setName("suggestButton"); // NOI18N
      suggestButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            suggestButtonActionPerformed(evt);
         }
      });

      labelWelcome.setBackground(new java.awt.Color(239, 240, 234));
      labelWelcome.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      labelWelcome.setForeground(new java.awt.Color(56, 133, 96));
      labelWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      labelWelcome.setText("Welcome. Please Sign In.");
      labelWelcome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      labelWelcome.setName("labelWelcome"); // NOI18N

      jMenuBar1.setName("jMenuBar1"); // NOI18N

      File.setText("File");
      File.setName("File"); // NOI18N

      jMenuNewRecipe.setText("New Recipe");
      jMenuNewRecipe.setName("jMenuNewRecipe"); // NOI18N
      jMenuNewRecipe.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuNewRecipeActionPerformed(evt);
         }
      });
      File.add(jMenuNewRecipe);

      jMenuSearchRecipe.setText("Search Recipes");
      jMenuSearchRecipe.setName("jMenuSearchRecipe"); // NOI18N
      jMenuSearchRecipe.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuSearchRecipeActionPerformed(evt);
         }
      });
      File.add(jMenuSearchRecipe);

      jSeparator1.setName("jSeparator1"); // NOI18N
      File.add(jSeparator1);

      jMenuPlaylist.setText("Recipe Collections");
      jMenuPlaylist.setName("jMenuPlaylist"); // NOI18N
      jMenuPlaylist.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuPlaylistActionPerformed(evt);
         }
      });
      File.add(jMenuPlaylist);

      jMenuSuggest.setText("Recipe Suggestions");
      jMenuSuggest.setName("jMenuSuggest"); // NOI18N
      jMenuSuggest.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuSuggestActionPerformed(evt);
         }
      });
      File.add(jMenuSuggest);

      jSeparator2.setName("jSeparator2"); // NOI18N
      File.add(jSeparator2);

      jMenuExit.setText("Exit");
      jMenuExit.setName("jMenuExit"); // NOI18N
      jMenuExit.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuExitActionPerformed(evt);
         }
      });
      File.add(jMenuExit);

      jMenuBar1.add(File);

      Profile.setText("Profile");
      Profile.setName("Profile"); // NOI18N

      jMenuViewProfile.setText("View Profile");
      jMenuViewProfile.setName("jMenuViewProfile"); // NOI18N
      jMenuViewProfile.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuViewProfileActionPerformed(evt);
         }
      });
      Profile.add(jMenuViewProfile);

      jMenuCreateProfile.setText("New Profile");
      jMenuCreateProfile.setName("jMenuCreateProfile"); // NOI18N
      jMenuCreateProfile.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuCreateProfileActionPerformed(evt);
         }
      });
      Profile.add(jMenuCreateProfile);

      jSeparator3.setName("jSeparator3"); // NOI18N
      Profile.add(jSeparator3);

      jMenuSignIn.setText("Sign In");
      jMenuSignIn.setName("jMenuSignIn"); // NOI18N
      jMenuSignIn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuSignInActionPerformed(evt);
         }
      });
      Profile.add(jMenuSignIn);

      jMenuBar1.add(Profile);

      Help.setText("Help");
      Help.setName("Help"); // NOI18N

      jMenuHelp.setText("Help Contents");
      jMenuHelp.setName("jMenuHelp"); // NOI18N
      jMenuHelp.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuHelpActionPerformed(evt);
         }
      });
      Help.add(jMenuHelp);

      jSeparator4.setName("jSeparator4"); // NOI18N
      Help.add(jSeparator4);

      jMenuAbout.setText("About");
      jMenuAbout.setName("jMenuAbout"); // NOI18N
      jMenuAbout.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuAboutActionPerformed(evt);
         }
      });
      Help.add(jMenuAbout);

      jMenuBar1.add(Help);

      setJMenuBar(jMenuBar1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(78, 78, 78)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(newRecipeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(playlistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(suggestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(labelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(signInButton))
            .addContainerGap(69, Short.MAX_VALUE))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel1)
                  .addGap(9, 9, 9)
                  .addComponent(jLabel3)
                  .addGap(6, 6, 6)
                  .addComponent(jLabel4)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addGap(132, 132, 132)
                  .addComponent(jLabel6)))
            .addGap(42, 42, 42))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(jLabel3)
               .addComponent(jLabel4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel6)
            .addGap(18, 18, 18)
            .addComponent(labelWelcome)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(newRecipeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(playlistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(suggestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(signInButton)
            .addContainerGap(17, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
		if (signedInProfile != null) {
			SearchRecipe searchRecipes = new SearchRecipe(this, true, recdao, signedInProfile, playdao, this);
			searchRecipes.setLocationRelativeTo(this);
			searchRecipes.setVisible(true);
		} else {
			NoProfile profile = new NoProfile(this, true, prodao, playdao, this);
			profile.setLocationRelativeTo(this);
			profile.setVisible(true);
		}
   }//GEN-LAST:event_searchButtonActionPerformed

    private void newRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRecipeButtonActionPerformed
		 if (signedInProfile != null) {
			 NewRecipe newRecipe = new NewRecipe(this, true, recdao);
			 newRecipe.setLocationRelativeTo(this);
			 newRecipe.setVisible(true);
		 } else {
			 NoProfile profile = new NoProfile(this, true, prodao, playdao, this);
			 profile.setLocationRelativeTo(this);
			 profile.setVisible(true);
		 }

    }//GEN-LAST:event_newRecipeButtonActionPerformed

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
		 if (signInButton.getText() == "Sign In") {
			 SignInScreen login = new SignInScreen(prodao, playdao, this);
			 login.setLocationRelativeTo(this);
			 login.setVisible(true);
			 InputStream music;  
		 } else {
			 signOut();
		 }
    }//GEN-LAST:event_signInButtonActionPerformed

    private void playlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playlistButtonActionPerformed
		 if (signedInProfile != null) {
			 PlayListSearch showPlaylists = new PlayListSearch(this, true, recdao, playdao, prodao, signedInProfile, this);
			 showPlaylists.setLocationRelativeTo(this);
			 showPlaylists.setVisible(true);
		 } else {
			 NoProfile profile = new NoProfile(this, true, prodao, playdao, this);
			 profile.setLocationRelativeTo(this);
			 profile.setVisible(true);
		 }
    }//GEN-LAST:event_playlistButtonActionPerformed

    private void suggestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suggestButtonActionPerformed
		 if (signedInProfile != null) {
			 Recipe item = recdao.suggestSomething(signedInProfile.getUserID());
			 Suggestion suggest = new Suggestion(this, true, item, recdao, signedInProfile);
			 suggest.setLocationRelativeTo(this);
			 suggest.setVisible(true);

		 } else {
			 NoProfile profile = new NoProfile(this, true, prodao, playdao, this);
			 profile.setLocationRelativeTo(this);
			 profile.setVisible(true);
		 }
    }//GEN-LAST:event_suggestButtonActionPerformed

    private void jMenuNewRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNewRecipeActionPerformed
		 if (signedInProfile != null) {
			 NewRecipe newRecipe = new NewRecipe(this, true, recdao);
			 newRecipe.setLocationRelativeTo(this);
			 newRecipe.setVisible(true);
		 } else {
			 NoProfile profile = new NoProfile(this, true, prodao, playdao, this);
			 profile.setLocationRelativeTo(this);
			 profile.setVisible(true);
		 }
    }//GEN-LAST:event_jMenuNewRecipeActionPerformed

    private void jMenuSearchRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSearchRecipeActionPerformed
		 SearchRecipe searchRecipes = new SearchRecipe(this, true, recdao, signedInProfile, playdao, this);
		 searchRecipes.setLocationRelativeTo(this);
		 searchRecipes.setVisible(true);
    }//GEN-LAST:event_jMenuSearchRecipeActionPerformed

    private void jMenuPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPlaylistActionPerformed
		 if (signedInProfile != null) {
			 PlayListSearch showPlaylists = new PlayListSearch(this, true, recdao, playdao, prodao, signedInProfile, this);
			 showPlaylists.setLocationRelativeTo(this);
			 showPlaylists.setVisible(true);
		 } else {
			 NoProfile profile = new NoProfile(this, true, prodao, playdao, this);
			 profile.setLocationRelativeTo(this);
			 profile.setVisible(true);
		 }
    }//GEN-LAST:event_jMenuPlaylistActionPerformed

    private void jMenuSuggestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSuggestActionPerformed
		 if (signedInProfile != null) {
			 Recipe item = recdao.suggestSomething(signedInProfile.getUserID());
			 Suggestion suggest = new Suggestion(this, true, item, recdao, signedInProfile);
			 suggest.setLocationRelativeTo(this);
			 suggest.setVisible(true);

		 } else {
			 NoProfile profile = new NoProfile(this, true, prodao, playdao, this);
			 profile.setLocationRelativeTo(this);
			 profile.setVisible(true);
		 }
    }//GEN-LAST:event_jMenuSuggestActionPerformed

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
		 recdao.closeDB();
		 System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jMenuCreateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCreateProfileActionPerformed
		 CreateProfile newProfile = new CreateProfile(this, true, prodao, playdao, this);
		 newProfile.setLocationRelativeTo(this);
		 newProfile.setVisible(true);
    }//GEN-LAST:event_jMenuCreateProfileActionPerformed

    private void jMenuViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuViewProfileActionPerformed
		 if (signedInProfile != null && "Dev".equals(signedInProfile.getName())) {
			 YesProfileDev devProfile = new YesProfileDev(this, true, signedInProfile, prodao, this);
			 devProfile.setLocationRelativeTo(this);
			 devProfile.setVisible(true);	 
			 
		 } else if (signedInProfile != null) {
			 YesProfile profile = new YesProfile(this, true, signedInProfile, prodao, playdao, this);
			 profile.setLocationRelativeTo(this);
			 profile.setVisible(true);
		 } else {
			 NoProfile profile = new NoProfile(this, true, prodao, playdao, this);
			 profile.setLocationRelativeTo(this);
			 profile.setVisible(true);
		 }
    }//GEN-LAST:event_jMenuViewProfileActionPerformed

    private void jMenuSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSignInActionPerformed
		 if (jMenuSignIn.getText() == "Sign In") {
			 SignInScreen login = new SignInScreen(prodao, playdao, this);
			 login.setLocationRelativeTo(this);
			 login.setVisible(true);
		 } else {
			 signOut();
		 }
    }//GEN-LAST:event_jMenuSignInActionPerformed

    private void jMenuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHelpActionPerformed
		 Help help = new Help();
		 help.setLocationRelativeTo(this);
		 help.setVisible(true);
    }//GEN-LAST:event_jMenuHelpActionPerformed

    private void jMenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAboutActionPerformed
		 About about = new About();
		 about.setLocationRelativeTo(this);
		 about.setVisible(true);
    }//GEN-LAST:event_jMenuAboutActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JMenu File;
   private javax.swing.JMenu Help;
   private javax.swing.JMenu Profile;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JMenuItem jMenuAbout;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JMenuItem jMenuCreateProfile;
   private javax.swing.JMenuItem jMenuExit;
   private javax.swing.JMenuItem jMenuHelp;
   private javax.swing.JMenuItem jMenuNewRecipe;
   private javax.swing.JMenuItem jMenuPlaylist;
   private javax.swing.JMenuItem jMenuSearchRecipe;
   private javax.swing.JMenuItem jMenuSignIn;
   private javax.swing.JMenuItem jMenuSuggest;
   private javax.swing.JMenuItem jMenuViewProfile;
   private javax.swing.JPopupMenu.Separator jSeparator1;
   private javax.swing.JPopupMenu.Separator jSeparator2;
   private javax.swing.JPopupMenu.Separator jSeparator3;
   private javax.swing.JPopupMenu.Separator jSeparator4;
   private javax.swing.JLabel labelWelcome;
   private javax.swing.JButton newRecipeButton;
   private javax.swing.JButton playlistButton;
   private javax.swing.JButton searchButton;
   private javax.swing.JButton signInButton;
   private javax.swing.JButton suggestButton;
   // End of variables declaration//GEN-END:variables
}
