/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ProfileDataInterface;
import dao.PlaylistDataInterface;
import domain.Profile;
import gui.helpers.SimpleListModel;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Hyunsun
 */
public class SignInScreen extends javax.swing.JFrame {
	
	private ProfileDataInterface prodao;
	private PlaylistDataInterface playdao;
	private SimpleListModel myModel = new SimpleListModel();
        private static MainMenu passThrough;

    /**
     * Creates new form NoProfile
     */
    public SignInScreen(ProfileDataInterface prodao, PlaylistDataInterface playdao, MainMenu passThrough) {
        this.prodao = prodao;
		  this.playdao = playdao;
        this.passThrough = passThrough;
        initComponents();
        this.setResizable(false);
        Color backgroundColor = new Color(229, 214, 201);
                this.getContentPane().setBackground(backgroundColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      jLabel7 = new javax.swing.JLabel();
      jLabel8 = new javax.swing.JLabel();
      jLabel9 = new javax.swing.JLabel();
      signInButton = new javax.swing.JButton();
      goBackButton = new javax.swing.JButton();
      createProfileButton = new javax.swing.JButton();
      jLabel11 = new javax.swing.JLabel();
      jLabel12 = new javax.swing.JLabel();
      jLabel13 = new javax.swing.JLabel();
      txtUsername = new javax.swing.JTextField();
      txtPassword = new javax.swing.JPasswordField();

      jLabel1.setBackground(new java.awt.Color(239, 240, 234));
      jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 36)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(75, 68, 41));
      jLabel1.setText("S E A R C H");

      jLabel3.setBackground(new java.awt.Color(239, 240, 234));
      jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel3.setForeground(new java.awt.Color(139, 191, 166));
      jLabel3.setText("Bone");

      jLabel4.setBackground(new java.awt.Color(239, 240, 234));
      jLabel4.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel4.setForeground(new java.awt.Color(255, 167, 167));
      jLabel4.setText("Apple");

      jLabel5.setBackground(new java.awt.Color(239, 240, 234));
      jLabel5.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel5.setForeground(new java.awt.Color(139, 191, 166));
      jLabel5.setText("Tea");

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setBackground(new java.awt.Color(239, 240, 234));

      jLabel2.setBackground(new java.awt.Color(239, 240, 234));
      jLabel2.setFont(new java.awt.Font("맑은 고딕", 1, 36)); // NOI18N
      jLabel2.setForeground(new java.awt.Color(75, 68, 41));
      jLabel2.setText("S I G N  I N");

      jLabel6.setBackground(new java.awt.Color(239, 240, 234));
      jLabel6.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel6.setForeground(new java.awt.Color(139, 191, 166));
      jLabel6.setText("Bone");

      jLabel7.setBackground(new java.awt.Color(239, 240, 234));
      jLabel7.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel7.setForeground(new java.awt.Color(255, 167, 167));
      jLabel7.setText("Apple");

      jLabel8.setBackground(new java.awt.Color(239, 240, 234));
      jLabel8.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel8.setForeground(new java.awt.Color(139, 191, 166));
      jLabel8.setText("Tea");

      jLabel9.setBackground(new java.awt.Color(239, 240, 234));
      jLabel9.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel9.setForeground(new java.awt.Color(56, 133, 96));
      jLabel9.setText("Please Log In:");

      signInButton.setBackground(new java.awt.Color(75, 68, 41));
      signInButton.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
      signInButton.setForeground(new java.awt.Color(255, 255, 255));
      signInButton.setText("SIGN IN");
      signInButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            signInButtonActionPerformed(evt);
         }
      });

      goBackButton.setBackground(new java.awt.Color(239, 240, 234));
      goBackButton.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
      goBackButton.setForeground(new java.awt.Color(71, 71, 71));
      goBackButton.setText("GO BACK TO MENU");
      goBackButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            goBackButtonActionPerformed(evt);
         }
      });

      createProfileButton.setBackground(new java.awt.Color(75, 68, 41));
      createProfileButton.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
      createProfileButton.setForeground(new java.awt.Color(255, 255, 255));
      createProfileButton.setText("CREATE PROFILE");
      createProfileButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            createProfileButtonActionPerformed(evt);
         }
      });

      jLabel11.setBackground(new java.awt.Color(239, 240, 234));
      jLabel11.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel11.setForeground(new java.awt.Color(56, 133, 96));
      jLabel11.setText("Username:");

      jLabel12.setBackground(new java.awt.Color(239, 240, 234));
      jLabel12.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel12.setForeground(new java.awt.Color(56, 133, 96));
      jLabel12.setText("Password:");

      jLabel13.setBackground(new java.awt.Color(239, 240, 234));
      jLabel13.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel13.setForeground(new java.awt.Color(56, 133, 96));
      jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel13.setText("Don't have a profile?");

      txtUsername.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
      txtUsername.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtUsernameActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(85, 85, 85)
            .addComponent(jLabel2)
            .addGap(0, 0, Short.MAX_VALUE))
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(18, 18, 18)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jLabel12)
                     .addComponent(jLabel11))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                     .addComponent(txtPassword)))
               .addGroup(layout.createSequentialGroup()
                  .addGap(127, 127, 127)
                  .addComponent(jLabel9))
               .addGroup(layout.createSequentialGroup()
                  .addGap(103, 103, 103)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                     .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(createProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(goBackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addContainerGap(34, Short.MAX_VALUE))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(jLabel6)
                  .addGap(9, 9, 9)
                  .addComponent(jLabel7)
                  .addGap(6, 6, 6)
                  .addComponent(jLabel8)
                  .addGap(65, 65, 65))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(signInButton)
                  .addGap(133, 133, 133))))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel6)
               .addComponent(jLabel7)
               .addComponent(jLabel8))
            .addGap(18, 18, 18)
            .addComponent(jLabel9)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel11)
               .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtPassword))
            .addGap(18, 18, 18)
            .addComponent(signInButton)
            .addGap(19, 19, 19)
            .addComponent(jLabel13)
            .addGap(18, 18, 18)
            .addComponent(createProfileButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(goBackButton)
            .addGap(21, 21, 21))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
		String username = txtUsername.getText();
		 String password = txtPassword.getText();

		 Profile profile1 = prodao.getProfileByUsername(username);
	 
		 if (profile1 != null && prodao.signIn(username, password)) {
				 Profile profileToSignIn = prodao.getProfileByUsername(username);
				 passThrough.signIn(profileToSignIn);
				 dispose();
			 } else {
				 JOptionPane.showMessageDialog(this, "Username or Password incorrect.", "Error",
							JOptionPane.WARNING_MESSAGE);
			 }

//		ViewProfiles viewProf = new ViewProfiles(this, true, prodao, passThrough);
//      viewProf.setLocationRelativeTo(this);
//      dispose();
//      viewProf.setVisible(true);     
    }//GEN-LAST:event_signInButtonActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
		 dispose();
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void createProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProfileButtonActionPerformed
		 CreateProfile newProfile = new CreateProfile(this, true, prodao, playdao, passThrough);
		 newProfile.setLocationRelativeTo(this);
		 newProfile.setVisible(true);
		 dispose();
    }//GEN-LAST:event_createProfileButtonActionPerformed

   private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtUsernameActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NoProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NoProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NoProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NoProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NoProfile().setVisible(true);
//            }
//        });
//    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton createProfileButton;
   private javax.swing.JButton goBackButton;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel11;
   private javax.swing.JLabel jLabel12;
   private javax.swing.JLabel jLabel13;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JButton signInButton;
   private javax.swing.JPasswordField txtPassword;
   private javax.swing.JTextField txtUsername;
   // End of variables declaration//GEN-END:variables
}
