/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.RecipeDataInterface;
import domain.Profile;
import domain.Recipe;
import gui.helpers.SimpleListModel;
import gui.helpers.ValidationHelper;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;

/**
 *
 * @author owner
 */
public class Suggestion extends javax.swing.JDialog {

    private final RecipeDataInterface dao;
    private SimpleListModel myModel = new SimpleListModel();
    private Recipe recipe = new Recipe();
    private ValidationHelper validHelp = new ValidationHelper();
    private Profile profile;

    /**
     * Creates new form Suggestion
     *
     * @param parent
     * @param modal
     * @param dao
     */
    public Suggestion(java.awt.Frame parent, boolean modal, RecipeDataInterface dao) {
        super(parent);
        super.setModal(modal);
        this.dao = dao;
        initComponents();
        this.setResizable(false);
        Color backgroundColor = new Color(229, 214, 201);
        this.getContentPane().setBackground(backgroundColor);
    }

    public Suggestion(java.awt.Frame parent, boolean modal, Recipe suggestedRecipe, RecipeDataInterface dao, Profile profile) {
        this(parent, modal, dao);
        this.recipe = suggestedRecipe;
        this.profile = profile;
        txtRecipeName.setText(recipe.getName());
        txtRecipeDescription.setText(recipe.getDescription());
        txtRecipeIngredients.setText(recipe.getIngredients());
        txtRecipeMethod.setText(recipe.getMethod());
        txtServingSize.setText(recipe.getServingSize());
        txtPrepTime.setText(recipe.getPrepTime());
//		//grabbing the tags
//		if (recipe.getTags().contains("Vegetarian")) {
//			jCheckBoxVegetarian.setSelected(true);
//		}
//		if (recipe.getTags().contains("Vegan")) {
//			jCheckBoxVegan.setSelected(true);
//		}
//		if (recipe.getTags().contains("Gluten Free")) {
//			jCheckBoxGF.setSelected(true);
//		}
//		if (recipe.getTags().contains("Dairy Free")) {
//			jCheckBoxDF.setSelected(true);
//		}
//		if (recipe.getTags().contains("Other")) {
//			jCheckBoxOther.setSelected(true);
//		}
        List<String> tags = new ArrayList<>();
        tags.addAll(recipe.getTags());
        StringBuilder fullTag = new StringBuilder("");
        for (int i = 0; i < tags.size(); i++) {
            if (i == tags.size() - 1) {
                fullTag.append(tags.get(i));
            } else {
                fullTag.append(tags.get(i) + ", ");
            }
        }
        txtTags.setText(fullTag.toString());
        txtTags.setEditable(false);
        txtRecipeName.setEditable(false);
        txtRecipeDescription.setEditable(false);
        txtRecipeIngredients.setEditable(false);
        txtRecipeMethod.setEditable(false);
        txtServingSize.setEditable(false);
        txtPrepTime.setEditable(false);

//                jCheckBoxVegetarian.setEnabled(false);
//                jCheckBoxVegan.setEnabled(false);
//                jCheckBoxGF.setEnabled(false);
//                jCheckBoxDF.setEnabled(false);
//                jCheckBoxOther.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRecipeName1 = new javax.swing.JTextField();
        txtRecipeName2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtRecipeName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtServingSize = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPrepTime = new javax.swing.JTextField();
        suggestButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        recipeCloseButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRecipeIngredients = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRecipeMethod = new javax.swing.JTextArea();
        txtTags = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtRecipeDescription = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();

        jLabel3.setBackground(new java.awt.Color(239, 240, 234));
        jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(139, 191, 166));
        jLabel3.setText("Bone");

        jLabel4.setBackground(new java.awt.Color(239, 240, 234));
        jLabel4.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 167, 167));
        jLabel4.setText("Apple");

        jLabel5.setBackground(new java.awt.Color(239, 240, 234));
        jLabel5.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(139, 191, 166));
        jLabel5.setText("Tea");

        txtRecipeName1.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        txtRecipeName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecipeName1ActionPerformed(evt);
            }
        });

        txtRecipeName2.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        txtRecipeName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecipeName2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setBackground(new java.awt.Color(239, 240, 234));
        jLabel6.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(139, 191, 166));
        jLabel6.setText("Bone");

        jLabel7.setBackground(new java.awt.Color(239, 240, 234));
        jLabel7.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 167, 167));
        jLabel7.setText("Apple");

        jLabel8.setBackground(new java.awt.Color(239, 240, 234));
        jLabel8.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(139, 191, 166));
        jLabel8.setText("Tea");

        jLabel1.setBackground(new java.awt.Color(239, 240, 234));
        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(75, 68, 41));
        jLabel1.setText("S U G G E S T I O N S");

        txtRecipeName.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        txtRecipeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecipeNameActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(239, 240, 234));
        jLabel9.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(56, 133, 96));
        jLabel9.setText("Name:");

        jLabel10.setBackground(new java.awt.Color(239, 240, 234));
        jLabel10.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(56, 133, 96));
        jLabel10.setText("Preparation Time:");

        txtServingSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServingSizeActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(239, 240, 234));
        jLabel11.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(56, 133, 96));
        jLabel11.setText("Method:");

        jLabel12.setBackground(new java.awt.Color(239, 240, 234));
        jLabel12.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(56, 133, 96));
        jLabel12.setText("Serving Size:");

        jLabel13.setBackground(new java.awt.Color(239, 240, 234));
        jLabel13.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(56, 133, 96));
        jLabel13.setText("Description:");

        txtPrepTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrepTimeActionPerformed(evt);
            }
        });

        suggestButton.setBackground(new java.awt.Color(75, 68, 41));
        suggestButton.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        suggestButton.setForeground(new java.awt.Color(255, 255, 255));
        suggestButton.setText("Suggest Something Else");
        suggestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suggestButtonActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(239, 240, 234));
        jLabel14.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(56, 133, 96));
        jLabel14.setText("Ingredients:");

        recipeCloseButton.setBackground(new java.awt.Color(75, 68, 41));
        recipeCloseButton.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        recipeCloseButton.setForeground(new java.awt.Color(255, 255, 255));
        recipeCloseButton.setText("CLOSE");
        recipeCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipeCloseButtonActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(239, 240, 234));
        jLabel15.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(56, 133, 96));
        jLabel15.setText("Dietary Tags:");

        txtRecipeIngredients.setColumns(20);
        txtRecipeIngredients.setLineWrap(true);
        txtRecipeIngredients.setRows(5);
        txtRecipeIngredients.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtRecipeIngredients);

        txtRecipeMethod.setColumns(20);
        txtRecipeMethod.setLineWrap(true);
        txtRecipeMethod.setRows(5);
        txtRecipeMethod.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtRecipeMethod);

        txtTags.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        txtTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTagsActionPerformed(evt);
            }
        });

        txtRecipeDescription.setColumns(20);
        txtRecipeDescription.setLineWrap(true);
        txtRecipeDescription.setRows(5);
        txtRecipeDescription.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtRecipeDescription);

        jLabel16.setBackground(new java.awt.Color(239, 240, 234));
        jLabel16.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(56, 133, 96));
        jLabel16.setText("(mins)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTags))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel13))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtServingSize, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPrepTime)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11)
                                        .addGap(93, 93, 93))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(suggestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(recipeCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane2))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRecipeName, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8))
                                    .addComponent(jLabel1))
                                .addGap(117, 117, 117)))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRecipeName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtServingSize, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPrepTime, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTags, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suggestButton)
                    .addComponent(recipeCloseButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRecipeName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecipeName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecipeName1ActionPerformed

    private void txtRecipeName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecipeName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecipeName2ActionPerformed

    private void txtRecipeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecipeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecipeNameActionPerformed

    private void txtServingSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServingSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServingSizeActionPerformed

    private void txtPrepTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrepTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrepTimeActionPerformed

    private void suggestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suggestButtonActionPerformed
//        jCheckBoxVegetarian.setSelected(false);
//        jCheckBoxVegan.setSelected(false);
//        jCheckBoxGF.setSelected(false);
//        jCheckBoxDF.setSelected(false);
//        jCheckBoxOther.setSelected(false);
        Recipe item = dao.suggestSomething(profile.getUserID());
        if (item.getName().equals(txtRecipeName.getText())) {
            item = dao.suggestSomething(profile.getUserID());
        } else {
            txtRecipeName.setText(item.getName());
            txtRecipeDescription.setText(item.getDescription());
            txtRecipeIngredients.setText(item.getIngredients());
            txtRecipeMethod.setText(item.getMethod());
            txtServingSize.setText(item.getServingSize());
            txtPrepTime.setText(item.getPrepTime());
            //grabbing the tags
//            if (item.getTags().contains("Vegetarian")) {
//                jCheckBoxVegetarian.setSelected(true);
//            }
//            if (item.getTags().contains("Vegan")) {
//                jCheckBoxVegan.setSelected(true);
//            }
//            if (item.getTags().contains("Gluten Free")) {
//                jCheckBoxGF.setSelected(true);
//            }
//            if (item.getTags().contains("Dairy Free")) {
//                jCheckBoxDF.setSelected(true);
//            }
//            if (item.getTags().contains("Other")) {
//                jCheckBoxOther.setSelected(true);
//            }
            List<String> tags = new ArrayList<>();
            tags.addAll(item.getTags());
            StringBuilder fullTag = new StringBuilder("");
            for (int i = 0; i < tags.size(); i++) {
                if (i == tags.size() - 1) {
                    fullTag.append(tags.get(i));
                } else {
                    fullTag.append(tags.get(i) + ", ");
                }
            }
            txtTags.setText(fullTag.toString());

            txtRecipeName.revalidate();
            txtRecipeDescription.revalidate();
            txtRecipeIngredients.revalidate();
            txtRecipeMethod.revalidate();
            txtServingSize.revalidate();
            txtPrepTime.revalidate();
            txtTags.revalidate();
//            jCheckBoxVegetarian.revalidate();
//            jCheckBoxVegan.revalidate();
//            jCheckBoxGF.revalidate();
//            jCheckBoxDF.revalidate();
//            jCheckBoxOther.revalidate();
        }


    }//GEN-LAST:event_suggestButtonActionPerformed

//    public JCheckBox getjCheckBoxDF() {
//        return jCheckBoxDF;
//    }
//
//    public JCheckBox getjCheckBoxGF() {
//        return jCheckBoxGF;
//    }
//
//    public JCheckBox getjCheckBoxOther() {
//        return jCheckBoxOther;
//    }
//
//    public JCheckBox getjCheckBoxVegan() {
//        return jCheckBoxVegan;
//    }
//
//    public JCheckBox getjCheckBoxVegetarian() {
//        return jCheckBoxVegetarian;
//    }

    private void recipeCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipeCloseButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_recipeCloseButtonActionPerformed

    private void txtTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTagsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTagsActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Suggestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Suggestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Suggestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Suggestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Suggestion dialog = new Suggestion(new javax.swing.JFrame(), true,dao);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton recipeCloseButton;
    private javax.swing.JButton suggestButton;
    private javax.swing.JTextField txtPrepTime;
    private javax.swing.JTextArea txtRecipeDescription;
    private javax.swing.JTextArea txtRecipeIngredients;
    private javax.swing.JTextArea txtRecipeMethod;
    private javax.swing.JTextField txtRecipeName;
    private javax.swing.JTextField txtRecipeName1;
    private javax.swing.JTextField txtRecipeName2;
    private javax.swing.JTextField txtServingSize;
    private javax.swing.JTextField txtTags;
    // End of variables declaration//GEN-END:variables
}
