/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ProfileDataInterface;
import domain.Profile;
import gui.helpers.SimpleListModel;
import java.awt.Color;

/**
 *
 * @author Hyunsun
 */
public class ViewProfiles extends javax.swing.JDialog {
	
	public ProfileDataInterface dao;
	private SimpleListModel myModel = new SimpleListModel();
        private MainMenu pushThrough;

	
    /**
     * Creates new form SearchRecipe
     */
    public ViewProfiles(java.awt.Window parent, boolean modal, ProfileDataInterface dao, MainMenu pushThrough) {
        super(parent);
		  super.setModal(modal);
        this.dao = dao;
        this.pushThrough = pushThrough;
        initComponents();
        myModel = new SimpleListModel();
        myModel.updateItems(dao.getAllProfiles());
        profileList.setModel(myModel);
        this.setResizable(false);
        Color backgroundColor = new Color(229, 214, 201);
                this.getContentPane().setBackground(backgroundColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      txtProfileSearch = new javax.swing.JTextField();
      profileList = new javax.swing.JList<>();
      signInButton = new javax.swing.JButton();
      closeButton = new javax.swing.JButton();
      searchButton = new javax.swing.JButton();
      deleteProfileButton = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setBackground(new java.awt.Color(239, 240, 234));

      jLabel1.setBackground(new java.awt.Color(239, 240, 234));
      jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 36)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(75, 68, 41));
      jLabel1.setText("S I G N  I N");

      jLabel3.setBackground(new java.awt.Color(239, 240, 234));
      jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel3.setForeground(new java.awt.Color(139, 191, 166));
      jLabel3.setText("Bone");

      jLabel4.setBackground(new java.awt.Color(239, 240, 234));
      jLabel4.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel4.setForeground(new java.awt.Color(255, 167, 167));
      jLabel4.setText("Apple");

      jLabel5.setBackground(new java.awt.Color(239, 240, 234));
      jLabel5.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel5.setForeground(new java.awt.Color(139, 191, 166));
      jLabel5.setText("Tea");

      txtProfileSearch.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
      txtProfileSearch.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtProfileSearchActionPerformed(evt);
         }
      });

      profileList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 162, 129)));

      signInButton.setBackground(new java.awt.Color(75, 68, 41));
      signInButton.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
      signInButton.setForeground(new java.awt.Color(255, 255, 255));
      signInButton.setText("SIGN IN");
      signInButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            signInButtonActionPerformed(evt);
         }
      });

      closeButton.setBackground(new java.awt.Color(75, 68, 41));
      closeButton.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
      closeButton.setForeground(new java.awt.Color(255, 255, 255));
      closeButton.setText("CLOSE");
      closeButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            closeButtonActionPerformed(evt);
         }
      });

      searchButton.setBackground(new java.awt.Color(94, 162, 129));
      searchButton.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
      searchButton.setForeground(new java.awt.Color(255, 255, 255));
      searchButton.setText("SEARCH");
      searchButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            searchButtonActionPerformed(evt);
         }
      });

      deleteProfileButton.setBackground(new java.awt.Color(75, 68, 41));
      deleteProfileButton.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
      deleteProfileButton.setForeground(new java.awt.Color(255, 255, 255));
      deleteProfileButton.setText("DELETE");
      deleteProfileButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            deleteProfileButtonActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(txtProfileSearch)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(signInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(deleteProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(28, 28, 28)
                  .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createSequentialGroup()
                  .addGap(187, 187, 187)
                  .addComponent(jLabel1)
                  .addGap(20, 205, Short.MAX_VALUE))
               .addComponent(profileList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addGap(226, 226, 226)
                  .addComponent(jLabel3)
                  .addGap(9, 9, 9)
                  .addComponent(jLabel4)
                  .addGap(6, 6, 6)
                  .addComponent(jLabel5)
                  .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(jLabel4)
               .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtProfileSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(profileList, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(signInButton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
               .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
               .addComponent(deleteProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
            .addGap(16, 16, 16))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
		 // TODO add your handling code here:
		 Profile profileToSignIn = profileList.getSelectedValue();
		 if (!profileList.isSelectionEmpty()) {
                     pushThrough.signIn(profileToSignIn);
                     dispose();
		 }
    }//GEN-LAST:event_signInButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
		  dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void txtProfileSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfileSearchActionPerformed
        System.out.println(txtProfileSearch.getText());
        myModel.updateItems(dao.getProfile(txtProfileSearch.getText()));
    }//GEN-LAST:event_txtProfileSearchActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        System.out.println(txtProfileSearch.getText());
        myModel.updateItems(dao.getProfile(txtProfileSearch.getText()));
    }//GEN-LAST:event_searchButtonActionPerformed

   private void deleteProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProfileButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_deleteProfileButtonActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SearchRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SearchRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SearchRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SearchRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                SearchRecipe dialog = new SearchRecipe(new javax.swing.JFrame(), true, dao);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Overrides
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton closeButton;
   private javax.swing.JButton deleteProfileButton;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JList<Profile> profileList;
   private javax.swing.JButton searchButton;
   private javax.swing.JButton signInButton;
   private javax.swing.JTextField txtProfileSearch;
   // End of variables declaration//GEN-END:variables
}
