/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.PlaylistDataInterface;
import dao.ProfileDataInterface;
import dao.RecipeDataInterface;
import domain.Recipe;
import domain.Profile;
import gui.helpers.SimpleListModel;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Hyunsun
 */
public class ViewRecipe extends javax.swing.JDialog {

	private final RecipeDataInterface dao;
	private ProfileDataInterface prodao;
	private PlaylistDataInterface playdao;
	private SimpleListModel myModel = new SimpleListModel();
	private Recipe recipe = new Recipe();
	private Profile signedInProfile;
	private java.awt.Window pushThroughParent;
	private MainMenu mm;

    /**
     * Creates new form ViewRecipe
     */
    public ViewRecipe(java.awt.Window parent, boolean modal, 
            RecipeDataInterface dao, Profile signedInProfile, PlaylistDataInterface playdao, MainMenu mm) {
        super(parent);
        super.setModal(modal);
        this.dao = dao;
		  this.playdao = playdao;
        this.signedInProfile = signedInProfile;
        this.pushThroughParent = parent;
        this.mm = mm;
        initComponents();
        this.setResizable(false);
        Color backgroundColor = new Color(229, 214, 201);
                this.getContentPane().setBackground(backgroundColor);
    }
	 
	 //constructor for VIEWING recipes
	 public ViewRecipe(java.awt.Window parent, boolean modal, 
			  Recipe recipeToEdit, RecipeDataInterface dao, Profile signedInProfile, PlaylistDataInterface playdao, MainMenu mm) {
		this(parent, modal, dao, signedInProfile, playdao, mm);
		this.recipe = recipeToEdit;
		txtRecipeName.setText(recipe.getName());
		txtRecipeName.setEditable(false);
		txtRecipeDescription.setText(recipe.getDescription());
		txtRecipeDescription.setEditable(false);
		txtRecipeIngredients.setText(recipe.getIngredients());
		txtRecipeIngredients.setEditable(false);
		txtRecipeMethod.setText(recipe.getMethod());
		txtRecipeMethod.setEditable(false);
		jtxtServingSize.setText(recipe.getServingSize());
		jtxtServingSize.setEditable(false);
		jtxtPrepTime.setText(recipe.getPrepTime());
		jtxtPrepTime.setEditable(false);
		//grabbing the tags
		List<String> tags = new ArrayList<>();
		tags.addAll(recipe.getTags());
		StringBuilder fullTag = new StringBuilder("");
		for(int i = 0;i < tags.size() ; i++){
			if(i == tags.size()-1){
				fullTag.append(tags.get(i));
			}else{
			fullTag.append(tags.get(i) + ", ");
			}
		}
		txtTags.setText(fullTag.toString());
		txtTags.setEditable(false);
                if (signedInProfile != null){
                    List<String> historyList = new ArrayList(
                    playdao.getHistory(signedInProfile.getUserID()));
                    if (!(historyList.contains(recipe.getRecipeID()))){
                        historyList.add(recipe.getRecipeID());
                        playdao.saveToHistory(signedInProfile.getUserID(), historyList);
                    }
                }
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      jLabel7 = new javax.swing.JLabel();
      jLabel8 = new javax.swing.JLabel();
      txtTags = new javax.swing.JTextField();
      recipeEditButton = new javax.swing.JButton();
      recipeCloseButton = new javax.swing.JButton();
      jLabel6 = new javax.swing.JLabel();
      jLabel10 = new javax.swing.JLabel();
      jtxtServingSize = new javax.swing.JTextField();
      jLabel11 = new javax.swing.JLabel();
      jtxtPrepTime = new javax.swing.JTextField();
      jLabel12 = new javax.swing.JLabel();
      jLabel9 = new javax.swing.JLabel();
      txtRecipeName = new javax.swing.JTextField();
      addToPlaylist = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      txtRecipeIngredients = new javax.swing.JTextArea();
      jScrollPane2 = new javax.swing.JScrollPane();
      txtRecipeMethod = new javax.swing.JTextArea();
      jScrollPane3 = new javax.swing.JScrollPane();
      txtRecipeDescription = new javax.swing.JTextArea();
      jLabel13 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setBackground(new java.awt.Color(239, 240, 234));

      jLabel1.setBackground(new java.awt.Color(239, 240, 234));
      jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 36)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(75, 68, 41));
      jLabel1.setText("R E C I P E");
      jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      jLabel3.setBackground(new java.awt.Color(239, 240, 234));
      jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel3.setForeground(new java.awt.Color(139, 191, 166));
      jLabel3.setText("Bone");

      jLabel4.setBackground(new java.awt.Color(239, 240, 234));
      jLabel4.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel4.setForeground(new java.awt.Color(255, 167, 167));
      jLabel4.setText("Apple");

      jLabel5.setBackground(new java.awt.Color(239, 240, 234));
      jLabel5.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel5.setForeground(new java.awt.Color(139, 191, 166));
      jLabel5.setText("Tea");

      jLabel7.setBackground(new java.awt.Color(239, 240, 234));
      jLabel7.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel7.setForeground(new java.awt.Color(56, 133, 96));
      jLabel7.setText("Method:");

      jLabel8.setBackground(new java.awt.Color(239, 240, 234));
      jLabel8.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel8.setForeground(new java.awt.Color(56, 133, 96));
      jLabel8.setText("Description:");

      txtTags.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
      txtTags.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtTagsActionPerformed(evt);
         }
      });

      recipeEditButton.setBackground(new java.awt.Color(75, 68, 41));
      recipeEditButton.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
      recipeEditButton.setForeground(new java.awt.Color(255, 255, 255));
      recipeEditButton.setText("EDIT");
      recipeEditButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            recipeEditButtonActionPerformed(evt);
         }
      });

      recipeCloseButton.setBackground(new java.awt.Color(75, 68, 41));
      recipeCloseButton.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
      recipeCloseButton.setForeground(new java.awt.Color(255, 255, 255));
      recipeCloseButton.setText("CLOSE");
      recipeCloseButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            recipeCloseButtonActionPerformed(evt);
         }
      });

      jLabel6.setBackground(new java.awt.Color(239, 240, 234));
      jLabel6.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel6.setForeground(new java.awt.Color(56, 133, 96));
      jLabel6.setText("Name:");

      jLabel10.setBackground(new java.awt.Color(239, 240, 234));
      jLabel10.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel10.setForeground(new java.awt.Color(56, 133, 96));
      jLabel10.setText("Preparation Time:");

      jtxtServingSize.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jtxtServingSizeActionPerformed(evt);
         }
      });

      jLabel11.setBackground(new java.awt.Color(239, 240, 234));
      jLabel11.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel11.setForeground(new java.awt.Color(56, 133, 96));
      jLabel11.setText("Serving Size:");

      jtxtPrepTime.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jtxtPrepTimeActionPerformed(evt);
         }
      });

      jLabel12.setBackground(new java.awt.Color(239, 240, 234));
      jLabel12.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel12.setForeground(new java.awt.Color(56, 133, 96));
      jLabel12.setText("Ingredients:");

      jLabel9.setBackground(new java.awt.Color(239, 240, 234));
      jLabel9.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel9.setForeground(new java.awt.Color(56, 133, 96));
      jLabel9.setText("Dietary Tags:");

      txtRecipeName.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
      txtRecipeName.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtRecipeNameActionPerformed(evt);
         }
      });

      addToPlaylist.setBackground(new java.awt.Color(75, 68, 41));
      addToPlaylist.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
      addToPlaylist.setForeground(new java.awt.Color(255, 255, 255));
      addToPlaylist.setText("ADD TO COLLECTION");
      addToPlaylist.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            addToPlaylistActionPerformed(evt);
         }
      });

      txtRecipeIngredients.setColumns(20);
      txtRecipeIngredients.setLineWrap(true);
      txtRecipeIngredients.setRows(5);
      txtRecipeIngredients.setWrapStyleWord(true);
      jScrollPane1.setViewportView(txtRecipeIngredients);

      txtRecipeMethod.setColumns(20);
      txtRecipeMethod.setLineWrap(true);
      txtRecipeMethod.setRows(5);
      txtRecipeMethod.setWrapStyleWord(true);
      jScrollPane2.setViewportView(txtRecipeMethod);

      txtRecipeDescription.setColumns(20);
      txtRecipeDescription.setLineWrap(true);
      txtRecipeDescription.setRows(5);
      txtRecipeDescription.setWrapStyleWord(true);
      jScrollPane3.setViewportView(txtRecipeDescription);

      jLabel13.setBackground(new java.awt.Color(239, 240, 234));
      jLabel13.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
      jLabel13.setForeground(new java.awt.Color(56, 133, 96));
      jLabel13.setText("(mins)");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(recipeEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(recipeCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addToPlaylist)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5)
                        .addGap(79, 79, 79))))
               .addGroup(layout.createSequentialGroup()
                  .addGap(117, 117, 117)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(82, 82, 82))
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2))))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtTags))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(jLabel6)
                           .addComponent(jLabel8)))
                     .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxtServingSize, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtPrepTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtRecipeName)
                        .addGap(142, 142, 142))
                     .addComponent(jScrollPane3))))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(addToPlaylist)
               .addComponent(jLabel1)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel3)
                  .addComponent(jLabel4)
                  .addComponent(jLabel5)))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel6)
               .addComponent(txtRecipeName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jtxtServingSize, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jtxtPrepTime, javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel11)
                  .addComponent(jLabel10))
               .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel8)
               .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel12)
               .addComponent(jLabel7))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jScrollPane1)
               .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtTags, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(recipeEditButton)
               .addComponent(recipeCloseButton)))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void txtTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTagsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTagsActionPerformed

    private void recipeEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipeEditButtonActionPerformed
		 EditRecipe editor = new EditRecipe(this, true, recipe, dao);
		 editor.setLocationRelativeTo(this);
		 editor.setVisible(true);
		 dispose();
    }//GEN-LAST:event_recipeEditButtonActionPerformed

    private void recipeCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipeCloseButtonActionPerformed
        // TODO add your handling code here:
		  dispose();
    }//GEN-LAST:event_recipeCloseButtonActionPerformed

    private void txtRecipeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecipeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecipeNameActionPerformed

    private void addToPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToPlaylistActionPerformed
        if (signedInProfile != null){	
            AddPlayList addToPlaylist = new AddPlayList(pushThroughParent, true, signedInProfile, playdao, recipe.getRecipeID());
            addToPlaylist.setLocationRelativeTo(this);
            addToPlaylist.setVisible(true);
        } else {
            NoProfile profile = new NoProfile(this, true, prodao, playdao, mm);
            profile.setLocationRelativeTo(this);
            profile.setVisible(true);
        }
    }//GEN-LAST:event_addToPlaylistActionPerformed

    private void jtxtPrepTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrepTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrepTimeActionPerformed

    private void jtxtServingSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtServingSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtServingSizeActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ViewRecipe dialog = new ViewRecipe(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton addToPlaylist;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel11;
   private javax.swing.JLabel jLabel12;
   private javax.swing.JLabel jLabel13;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JScrollPane jScrollPane3;
   private javax.swing.JTextField jtxtPrepTime;
   private javax.swing.JTextField jtxtServingSize;
   private javax.swing.JButton recipeCloseButton;
   private javax.swing.JButton recipeEditButton;
   private javax.swing.JTextArea txtRecipeDescription;
   private javax.swing.JTextArea txtRecipeIngredients;
   private javax.swing.JTextArea txtRecipeMethod;
   private javax.swing.JTextField txtRecipeName;
   private javax.swing.JTextField txtTags;
   // End of variables declaration//GEN-END:variables
}
